; Script generated by the Inno Setup Script Wizard and Claude Sonnet 4.6 by ABATBeliever.
; Please build via scripts/build.bat before run this iss file.
; Inno Setup is here : https://jrsoftware.org/isdl.ph
; (Recommend: 6.7.3)
; Do not locate in non-ASCII Path
#define MyAppName "Strollon WebBrowser"
#define MyAppVersion "1.2.0.0"
#define MyAppPublisher "ABATBeliever"
#define MyAppURL "https://abatbeliever.net/software/bin/Strollon"
#define MyAppExeName "Strollon.exe"
#define MyAppOutputName "Strollon-x64-Installer"
#define MyAppProgId "StrollonWebBrowser.x64.HTML"
[Setup]
AppId={{A67AD239-5AFC-418A-B86F-AE3382DB00A9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
VersionInfoVersion={#MyAppVersion}
VersionInfoDescription={#MyAppOutputName}
VersionInfoProductName={#MyAppOutputName}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
DefaultDirName={autopf}\StrollonWebBrowser
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=./LICENSE-inno.txt
;PrivilegesRequired=lowest
OutputDir=..\
OutputBaseFilename={#MyAppOutputName}
SetupIconFile=..\img\icon-win.ico
SolidCompression=yes
WizardStyle=classic
[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"
[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "registerbrowser"; Description: "Strollonを既定のブラウザの候補として登録する"; GroupDescription: "レジストリ操作:"
[Files]
Source: "..\Strollon.dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
[Registry]
; ---- ProgID本体 ----
Root: HKLM; Subkey: "Software\Classes\{#MyAppProgId}"; ValueType: string; ValueName: ""; ValueData: "Strollon HTML Document"; Flags: uninsdeletekey; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Classes\{#MyAppProgId}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"",0"; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Classes\{#MyAppProgId}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" -- ""%1"""; Tasks: registerbrowser

; ---- Capabilities ----
Root: HKLM; Subkey: "Software\Strollon"; Flags: uninsdeletekeyifempty; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Strollon\Capabilities"; ValueType: string; ValueName: "ApplicationName"; ValueData: "{#MyAppName}"; Flags: uninsdeletekey; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Strollon\Capabilities"; ValueType: string; ValueName: "ApplicationDescription"; ValueData: "Strollon WebBrowser"; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Strollon\Capabilities"; ValueType: string; ValueName: "ApplicationIcon"; ValueData: """{app}\{#MyAppExeName}"",0"; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Strollon\Capabilities\URLAssociations"; ValueType: string; ValueName: "http"; ValueData: "{#MyAppProgId}"; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Strollon\Capabilities\URLAssociations"; ValueType: string; ValueName: "https"; ValueData: "{#MyAppProgId}"; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Strollon\Capabilities\URLAssociations"; ValueType: string; ValueName: "ftp"; ValueData: "{#MyAppProgId}"; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Strollon\Capabilities\FileAssociations"; ValueType: string; ValueName: ".htm"; ValueData: "{#MyAppProgId}"; Tasks: registerbrowser
Root: HKLM; Subkey: "Software\Strollon\Capabilities\FileAssociations"; ValueType: string; ValueName: ".html"; ValueData: "{#MyAppProgId}"; Tasks: registerbrowser

; ---- RegisteredApplications: Windowsの「既定のアプリ」一覧にStrollonを載せる ----
Root: HKLM; Subkey: "Software\RegisteredApplications"; ValueType: string; ValueName: "Strollon"; ValueData: "Software\Strollon\Capabilities"; Flags: uninsdeletevalue; Tasks: registerbrowser
[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent